# this will hold the username and pwd for mongoDB app
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # generic type for creating secret data
data:
  mongo-user: bW9uZ291c2Vy # base64 encoded value of 'mongouser'
  mongo-password: bW9uZ29wYXNz # base64 encoded value of 'mongopass'