# config file containing Deployment and Service for the webapp

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 # when scaling db use statefulset and not deployment
  selector:
    matchLabels:
      app: webapp
  template:               # config of the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:         # list of containers inside the pod
      - name: webapp
        image: nanajanashia/k8s-demo-app:1.0
        ports:
        - containerPort: 3000 # should be the same as targetPort in service
      env:
      - name: USER_NAME
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            value: mongo-user
      - name: USER_PWD
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            value: mongo-password
      - name: DB_URL
        valueFrom:
          configMapKeyRef:
            name: mongo-config
            value: mongo-url


---
#service config
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  selector:           # selects pods to forward the reqs to
    app: webapp
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 3000     # Always the same as container port
  # type: ClusterIP






